# Load .bashrc if available
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

# Set PATHS
if [ -x "/opt/homebrew/bin/brew" ]; then
    # For Apple Silicon Macs
    export PATH="/opt/homebrew/bin:$PATH"
fi
export PATH=/opt/homebrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/java8path:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Python312/Scripts/:/mnt/c/Python312/:/mnt/c/ProgramData/Oracle/Java/javapath:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/nodejs/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/Tushya/AppData/Local/Programs/Python/Python311/Scripts/:/mnt/c/Users/Tushya/AppData/Local/Programs/Python/Python311/:/mnt/c/Program Files/MySQL/MySQL Shell 8.0/bin/:/mnt/c/Users/Tushya/AppData/Local/Programs/Python/Python310/Scripts/:/mnt/c/Users/Tushya/AppData/Local/Programs/Python/Python310/:/mnt/c/Users/Tushya/AppData/Local/Programs/Python/Python39/Scripts/:/mnt/c/Users/Tushya/AppData/Local/Programs/Python/Python39/:/mnt/c/Users/Tushya/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Tushya/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/msys64/ucrt64/bin:/mnt/c/Users/Tushya/AppData/Roaming/npm:/mnt/c/Program Files/Neovim/bin
export PATH=/opt/homebrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/java8path:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Python312/Scripts/:/mnt/c/Python312/:/mnt/c/ProgramData/Oracle/Java/javapath:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/nodejs/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/Tushya/AppData/Local/Programs/Python/Python311/Scripts/:/mnt/c/Users/Tushya/AppData/Local/Programs/Python/Python311/:/mnt/c/Program Files/MySQL/MySQL Shell 8.0/bin/:/mnt/c/Users/Tushya/AppData/Local/Programs/Python/Python310/Scripts/:/mnt/c/Users/Tushya/AppData/Local/Programs/Python/Python310/:/mnt/c/Users/Tushya/AppData/Local/Programs/Python/Python39/Scripts/:/mnt/c/Users/Tushya/AppData/Local/Programs/Python/Python39/:/mnt/c/Users/Tushya/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Tushya/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/msys64/ucrt64/bin:/mnt/c/Users/Tushya/AppData/Roaming/npm:/mnt/c/Program Files/Neovim/bin
source ~/.bashrc
