#!/usr/bin/env bash
set -euo pipefail

path=$(fd . "$HOME" --type directory --max-depth 4 | fzf)
if [ -z $path ]; then
  exit 1
fi
cd $path
echo -n "Session name: "
read name
tmux new-session -d -s $name
tmux switch-client -t $name
