#!/usr/bin/env bash

TOX_WIDTH="$1"
TOX_HEIGHT="$2"
TOX_TEXT_COLOR="$3"
TOX_BORDER_COLOR="$4"
TOX_TITLE="$5"

# curr_sess=$(tmux list-sessions | grep "attached" | sed -E 's/:.*$//')
curr_sess=$(tmux display-message -p '#S')
if echo "$curr_sess" | grep "popup"; then
  tmux detach-client
else
  popup_sess=$(printf "popup-$curr_sess")
  if ! tmux list-sessions | grep -q "^$popup_sess:"; then
    tmux new-session -d -c "$(tmux display-message -p '#{pane_current_path}')" -s "$popup_sess"
    tmux set-option -t "$popup_sess" detach-on-destroy on
  fi
  tmux popup \
    -S fg="$TOX_BORDER_COLOR" \
    -s fg="$TOX_TEXT_COLOR" \
    -T "$TOX_TITLE" \
    -w "$TOX_WIDTH" \
    -h "$TOX_HEIGHT" \
    -b rounded \
    -E \
    "tmux attach-session -t \"$popup_sess\"" 
fi

